apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jmx-exporter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jmx-exporter
    spec:
      containers:
      - name: jmx-exporter
        image: vageesha99/alpha:v1
        ports:
        - name: web
          containerPort: 8080
