apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: backend-monitor
  name: backend-monitor
  namespace: openshift-monitoring
spec:
  endpoints:
    - interval: 30s
      port: prom
  namespaceSelector:
    matchNames:
      - monitored-apps
  selector:
    matchLabels:
      team: backend
