kind: Service
apiVersion: v1
metadata:
  name: jmx-exporter
  labels:
    app: jmx-exporter
    team: backend
spec:
  selector:
    app: jmx-exporter
  ports:
  - name: web
    port: 8080
  - port: 8088
    name: prom
